# Generated by Django 4.0.5 on 2022-06-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveIntegerField(unique=True, verbose_name='заказ №')),
                ('price_usd', models.FloatField(default=0, verbose_name='стоимость, $')),
                ('price_rub', models.FloatField(default=0, verbose_name='стоимость, руб.')),
                ('delivery_date', models.DateField(verbose_name='срок поставки')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
    ]
